version: '2.1'

services:
  fantasy-baseball-server:
    image: fantasy-baseball-server
    build: .
    network_mode: ${NETWORK_MODE}
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://localhost:12201'
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
    ports:
      - ${PORT}:${PORT}
